name: Deploy Portfolio Website

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: portfolio-website

jobs:
  deploy:
    name: Deploy on santa-cruz
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build application
        run: dotnet publish -c Release -o published

      - name: Build image
        run: podman build -t $IMAGE_NAME .

      - name: Log in to registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          # echo VERSION=$VERSION
          podman tag $IMAGE_NAME $IMAGE_ID:latest
          podman push $IMAGE_ID:latest

      - name: Pull new image
        run: podman pull ghcr.io/eoncarlyle/portfolio-website:latest

      - name: Stop existing container
        run: podman stop $IMAGE_NAME && podman rm $IMAGE_NAME

      - name: Start new container
        run: podman run -d -p 4000:4000 --name=$IMAGE_NAME ghcr.io/eoncarlyle/$IMAGE_NAME:latest
