name: Deploy Portfolio Website

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: portfolio-website

jobs:
  deploy:
    name: Deploy on santa-cruz
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build application
        run: dotnet publish -c Release -o published

      - name: Log in to registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker build -t $IMAGE_ID:latest .

          # VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          # echo VERSION=$VERSION
          docker push $IMAGE_ID:latest

      - name: Pull new image
        run: docker pull ghcr.io/eoncarlyle/portfolio-website:latest

      - name: Stop and remove existing image
        run: docker container stop $IMAGE_NAME && docker container rm $IMAGE_NAME
        continue-on-error: true

      - name: Start new container
        run: docker run -d -p 4000:4000 --name=$IMAGE_NAME --replace ghcr.io/eoncarlyle/$IMAGE_NAME:latest
