name: Build and Deploy Container Images

on:
  push:
    branches:
      - main
    paths:
      - "portfolio-application/**"
      - ".github/workflows/**"

jobs:
  check_changes:
    runs-on: self-hosted
    outputs:
      portfolio_changed: ${{ steps.check_changes.outputs.portfolio_changed }}
      actions_changed: ${{ steps.check_changes.outputs.actions_changed }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes
        id: check_changes
        run: |
          git diff --name-only HEAD^ HEAD > changes.txt

          echo "Changed files:"
          cat changes.txt

          if grep -q "portfolio-application/" changes.txt; then
            echo "portfolio_changed=true" >> $GITHUB_OUTPUT
          else
            echo "portfolio_changed=false" >> $GITHUB_OUTPUT
          fi

          if grep -q "\.github/workflows/" changes.txt; then
            echo "actions_changed=true" >> $GITHUB_OUTPUT
          else
            echo "actions_changed=false" >> $GITHUB_OUTPUT
          fi

          echo "Final outputs:"
          echo "portfolio_changed: $(cat $GITHUB_OUTPUT | grep portfolio_changed)"
          echo "actions_changed: $(cat $GITHUB_OUTPUT | grep actions_changed)"

  build_portfolio:
    needs: check_changes
    if: needs.check_changes.outputs.portfolio_changed == 'true'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build Portfolio Application
        run: |
          cd portfolio-application
          dotnet publish -c Release
          sudo podman build -t localhost/portfolio-application:latest .

  setup_network:
    needs: [check_changes, build_portfolio]
    runs-on: self-hosted
    steps:
      - name: Setup Network
        run: |
          sudo podman network exists podman_bridge_rootfull || \
          sudo podman network create --driver bridge \
            --subnet 192.168.100.0/24 \
            --gateway 192.168.100.1 \
            podman_bridge_rootfull

  deploy_test:
    needs: [check_changes, build_portfolio, setup_network]
    if: always() && (needs.check_changes.outputs.portfolio_changed == 'true' || needs.check_changes.outputs.actions_changed == 'true')
    runs-on: self-hosted

    steps:
      - name: Deploy Portfolio Applications
        if: (needs.check_changes.outputs.actions_changed == 'true')|| (needs.check_changes.outputs.portfolio_changed == 'true')
        run: |
          for i in {1..2}; do
            sudo podman run -d \
              --name portfolio-application-$i-test \
              --replace \
              --network podman_bridge_rootfull \
              --ip 192.168.100.7$i \
              --tls-verify=false \
              localhost/portfolio-application:latest \
              192.168.100.7$i 1080
            sleep 1
          done

      - name: Verify Container Deployments
        run: |
          sudo podman ps --format "{{.Names}}: {{.Status}}"

      - name: Verify success
        run: |
          curl -I https://test.iainschmitt.com

  deploy_prod:
    needs: [deploy_test, build_portfolio, check_changes]
    if: always() && (needs.check_changes.outputs.portfolio_changed == 'true' || needs.check_changes.outputs.actions_changed == 'true')
    runs-on: self-hosted

    steps:
      - name: Deploy Portfolio Applications
        if: (needs.check_changes.outputs.actions_changed == 'true') || ( needs.check_changes.outputs.portfolio_changed == 'true')
        run: |
          for i in {1..2}; do
            sudo podman run -d \
              --name portfolio-application-$i \
              --replace \
              --network podman_bridge_rootfull \
              --ip 192.168.100.4$i \
              --tls-verify=false \
              localhost/portfolio-application:latest \
              192.168.100.4$i 1080
            sleep 5
          done

      - name: Verify Container Deployments
        run: |
          sudo podman ps --format "{{.Names}}: {{.Status}}"

      - name: Verify success
        run: |
          curl -I https://iainschmitt.com
