name: Deploy Portfolio Website

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: portfolio-website

jobs:
  deploy:
    name: Deploy on santa-cruz
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build application
        run: dotnet publish -c Release -o published

      - name: Remove runtime directory
        run: rm -rf /home/iain/portfolio-website

      - name: Coppying new runtime directory
        run: cp -r ../ /home/iain/portfolio-website

      - name: Restarting service
        run: systemctl --user restart portfolio-website
