name: Deploy Portfolio Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on santa-cruz
    runs-on: self-hosted

    steps:
      - name: Pull latest code from main branch
        run: git -C /home/iain/portfolio-website pull

      - name: Build Podman image
        run: runuser -u iain -- podman build -t portfolio-website:latest /home/iain/portfolio-website

      - name: Systemd daemon reload
        run: runuser -u iain -- systemctl --user daemon-reload

      - name: Restart quadlet service
        run: runuser -u iain -- systemctl --user restart quadlet-portfolio-website.service
