name: Deploy Portfolio Website

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: portfolio-website

jobs:
  deploy:
    name: Deploy on santa-cruz
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application
        run: dotnet publish -c Release -o published

      - name: Remove runtime directory
        run: rm -rf /home/iain/portfolio-website

      - name: Creating new runtime directory
        run: mkdir /home/iain/portfolio-website

      - name: Copying new runtime directory
        run: cp -r portfolio-website/bin/Release/net8.0/* /home/iain/portfolio-website

      - name: Restarting service
        run: sudo systemctl --user -M iain@ restart portfolio-website.service
