name: Test Deploy Portfolio Website

on:
  push:
    branches:
      - rediculous-deployment

jobs:
  deploy:
    name: Deploy on santa-cruz
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

       #Commenting these out for now
      - name: Build application
        run: dotnet publish -c Release -o published

      - name: Build container image
        run: podman build -t localhost/portfolio-website:latest .

      - name: Debug
        run: whoami

      - name: Run ZooKeeper container
        run: podman pull docker.io/library/zookeeper && podman run --name zookeeper-server --replace -d --network=host zookeeper:latest

      - name: Run first container
        run: podman run -d --network=host localhost/portfolio-website:latest 4001

