name: Build and Deploy Container Images to VPS

on:
  push:
    branches:
      - main
    paths:
      - "portfolio-application/**"
      - ".github/workflows/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/portfolio-application

jobs:
  build_and_push:
    runs-on: [self-hosted, new-york-0]

    permissions:
      contents: read
      packages: write

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate version info
        id: version
        run: |
          VERSION=$(date +'%Y.%m.%d').${{ github.run_number }}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Generated version: $VERSION"

      - name: Log in to the Container registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract metadata for container
        id: meta
        run: |
          # Create a sanitized version variable to ensure it's not empty
          VERSION_TAG="${VERSION:-latest}"
          echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION_TAG},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT

      - name: Build and push container image
        run: |
          cd ./portfolio-application
          # Make sure VERSION is not empty to avoid the parse error
          VERSION="${VERSION:-$(date +'%Y.%m.%d').${{ github.run_number }}}"

          # Build with the version tag
          sudo podman build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION} .
          sudo podman tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          sudo podman push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}
          sudo podman push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy_test:
    needs: build_and_push
    runs-on: [self-hosted, new-york-0]

    steps:
      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Setup Network
        run: |
          sudo podman network exists podman_bridge_rootfull || \
          sudo podman network create --driver bridge \
            --subnet 192.168.100.0/24 \
            --gateway 192.168.100.1 \
            podman_bridge_rootfull

      - name: Pull latest image
        run: |
          sudo podman pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build_and_push.outputs.version }}

      - name: Deploy to test environment
        run: |
          sudo podman run -d \
            --name portfolio-application-1-test \
            --replace \
            --network podman_bridge_rootfull \
            --ip 192.168.100.71 \
            --tls-verify=false \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build_and_push.outputs.version }} \
            192.168.100.71 1080

      - name: Verify Container Deployments
        run: |
          sudo podman ps --format "{{.Names}}: {{.Status}}"

      - name: Verify success
        run: |
          curl -I https://test.iainschmitt.com

  deploy_prod:
    needs: deploy_test
    runs-on: [self-hosted, new-york-0]

    steps:
      - name: Deploy to production environment
        run: |
          sudo podman run -d \
            --name portfolio-application-1 \
            --replace \
            --network podman_bridge_rootfull \
            --ip 192.168.100.41 \
            --tls-verify=false \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build_and_push.outputs.version }} \
            192.168.100.41 1080

      - name: Verify Container Deployments
        run: |
          sudo podman ps --format "{{.Names}}: {{.Status}}"

      - name: Verify success
        run: |
          curl -I https://iainschmitt.com
